#!/usr/bin/env php
<?php

declare(strict_types=1);

use Lite\Console\Kernel;

require __DIR__ . '/vendor/autoload.php';

/** @var Lite\Application $app */
$app = require __DIR__ . '/bootstrap/app.php';

exit((new Kernel($app))->run($argv));
